name: Cypress Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  cypress:
    runs-on: ubuntu-latest
    services:
      app:
        image: nginx:alpine
        ports:
          - 3000:80
        options: >-
          --health-cmd "curl -f http://localhost" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 3

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress Tests
        run: npm run test:ci

